OLD_USER_ID    = "old_user"
OLD_PASS       = "old_password"
OLD_DOMAIN     = "old.backlog.jp"
OLD_PROJECT    = "OLD_PROJ"

NEW_USER_ID    = "new_user"
NEW_PASS       = "new_pass"
NEW_DOMAIN     = "new.backlog.jp"
NEW_BASIC_ID   = "basic_id"
NEW_BASIC_PASS = "basic_pass"
NEW_PROJECT    = "NEW_PROJ"
